### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by okanduzyel** [maccoylton/esp-homekit-multi-sensor#4]
I am living same issue with that: https://github.com/maccoylton/esp-homekit-air-quality-sensor/issues/9

I cloned it with that code: **git clone --recursive https://github.com/maccoylton/esp-homekit-multi-sensor.git .**

Then, entered src folder and tried to execute that code: **make -C . test**

Result:

```
vagrant@vagrant-ubuntu-trusty-64:~/esp-homekit-demo/examples/esp-homekit-multi-sensor/src$ make -C . test
make: Entering directory `/home/vagrant/esp-homekit-demo/examples/esp-homekit-multi-sensor/src'
/home/vagrant/esp-open-rtos/common.mk:223: /home/vagrant/esp-homekit-demo/examples/esp-homekit-multi-sensor/components/esp-homekit/component.mk: No such file or directory
make: *** No rule to make target `/home/vagrant/esp-homekit-demo/examples/esp-homekit-multi-sensor/components/esp-homekit/component.mk'.  Stop.
make: Leaving directory `/home/vagrant/esp-homekit-demo/examples/esp-homekit-multi-sensor/src'
vagrant@vagrant-ubuntu-trusty-64:~/esp-homekit-demo/examples/esp-homekit-multi-sensor/src$
```

**Comment by maccoylton** [comment]
This is dependant on you  have a working esp-open-rtos build environment, instruction for that can be found here:- https://github.com/SuperHouse/esp-open-rtos. 

Alternatively check out the wiki for instructions on installing a pre-built firmware

**Comment by okanduzyel** [comment]
> Alternatively check out the wiki for instructions on installing a pre-built firmware

That is amazing, solved my problem quickly. 

Thanks a lot ✋🏻
