### ISSUE TITLE
Light sensor pooling time

### ISSUE THREAD

**Issue by okanduzyel** [maccoylton/esp-homekit-multi-sensor#5]
Hi, 

I did your project via OTA programming way at my home and It worked very well but I think, light sensor pooling time is too high. It reads around every 30 seconds. 

Why is it too high? Is there any way to decrease it around 5 sec. or more less? And if you update it on your GitHub page, my device automatically update itself?

**Comment by maccoylton** [comment]
I;ve changed this to 5 seconds. Using the Eve app if you hit the FirmwareUpdate button then it will reboot, connect to github, and pull own the latest version, then reboot.
