### ISSUE TITLE
Led blink request

### ISSUE THREAD

**Issue by okanduzyel** [maccoylton/esp-homekit-multi-sensor#6]
Hi,

Could you add led blink when it be pooling light? 
For Esp12E on board led connected to gpio 2. So,

First: **#define LED_GPIO 13** should change as **#define LED_GPIO 2**
Second: You can call a **led_code** function at the end of that task

```
void light_sensor_task(void *_args) {
    
    // thaks to https://github.com/peros550/esp-homekit-multiple-sensors/blob/master/examples/multiple_sensors/multiple_sensors.c
    
    int loop_count = 60;
    
    uint16_t analog_light_value;
    while (1) {
        analog_light_value = sdk_system_adc_read();
        //The below code does not produce accurate LUX readings which is what homekit expects. It only provides an indication of brightness on a scale between 0 to 1024
        //More work needs to be done so that accurate conversation to LUX scale can take place. However this is strongly dependent on the type of sensor used.
        //In my case I used a Photodiode Light Sensor
        currentAmbientLightLevel.value.float_value = (1024 - analog_light_value);
        homekit_characteristic_notify(&currentAmbientLightLevel, HOMEKIT_FLOAT((1024 - analog_light_value)));
        printf ("%s: Light level: %i\n", __func__, (1024 - analog_light_value));
        if (loop_count == 10){
            snprintf (post_string, 150, "sql=insert into homekit.lightsensorlog (LightSensorName, LightLevel) values ('%s', %f)", accessory_name, currentAmbientLightLevel.value.float_value);
            printf ("%s: Post String: %s\n", __func__, post_string);
            vTaskResume( http_post_tasks_handle );
            loop_count = 0;
        }
        vTaskDelay(5000 / portTICK_PERIOD_MS);

       // FOR EXAMPLE HERE //

        loop_count ++;
    }
}
```

I have designed a custom device with esp12e which is the most popular esp8266 module. I have put it in the box which I have designed as well. The box has transparent face and when the led of esp flickering, box look so nice. Indeed, sometimes, Esp crashes, I don't know why. So, It can help me to see If there is no led blink, I should do something for device.

_P.s: Unfortunately, there is no any chance to connect a led to default pin, gpio 13. I can only use on board led of esp. That's why I want that you change it._

**Comment by maccoylton** [comment]
Sorry this may  be good in your setup, but in my setup the box is not transparent and I therefore use and external LED. I also use ESP12E
