### ISSUE TITLE
QR CODE

### ISSUE THREAD

**Issue by ooomakon** [maccoylton/esp-homekit-multi-sensor#7]
Can`t find qr code?

**Comment by maccoylton** [comment]
Pair from within Home or Eve app, pin is all 1s

**Comment by ooomakon** [comment]
You need code to create a pair without it not added to the app

**Comment by ooomakon** [comment]
Asks for pairing code

**Comment by maccoylton** [comment]
> Asks for pairing code

As above code is all 1s

**Comment by ooomakon** [comment]
Setting code is not correct

**Comment by maccoylton** [comment]
Im really sorry I don't understand your issue. Once you have the firmware installed to your device you need to add the device using the Home or Eve app, the code is  "111-11-111". If you look in main.c you will see this on line 263

**Comment by ooomakon** [comment]
Спасибо, я разобрался,код принимается с 4-5 попытки иногда пишет что код не верный.

**Comment by maccoylton** [comment]
Thanks, I figured it out, the code is accepted after 4-5 attempts, sometimes it says that the code is not correct.


Are you using the binary or did you compile from latest sources?

**Comment by ooomakon** [comment]
Файл bootloader.bin версии 0.1.0 ,а 0.1.2 не сопрягалось
