### ISSUE TITLE
Adding library issue

### ISSUE THREAD

**Issue by muhammettufekci** [maccoylton/esp-homekit-multi-sensor#8]
Hello there. First of all, I apologize for my bad english. I am very new to Arduino and ESP8266 yet. When I try to add a library through the Arduino program, I get an error. I am attaching the link of the library I want to add. Maybe the file I'm trying to add isn't even a library. If this is not a library, how can I use files of this type?

https://github.com/maccoylton/esp-homekit-multi-sensor

**Comment by maccoylton** [comment]
This is not an Arduino library. This is a standalone firmware. The wiki give instructions on how to install the firmware
